### ISSUE TITLE
CAacDecoder_Open failed

### ISSUE THREAD

**Issue by aifer2007** [MrBuddyCasino/ESP32_MP3_Decoder#10]
ESP32_MP3_Decoder can play mp3 and acc files on my ESP32.

I want to run ESP32_MP3_Decoder in mongoose-os for ESP32. 

I do some code migration, Codes can be copmlied and linked with no errors.

Mp3/MAD part works well.

But AAC/fdk-aac part always reports `E (5264) fdkaac_decoder: malloc failed 90` when running.

In the code
```C
        /* create decoder instance */
        handle = aacDecoder_Open(TT_MP4_ADTS, /* num layers */1);
        if (handle == NULL) {
            ESP_LOGE(TAG, "malloc failed %d", __LINE__);
            goto cleanup;
        }
```

aacDecoder_Open always return NULL.

In file accdecoder.cpp

```C
LINKSPEC_CPP HANDLE_AACDECODER CAacDecoder_Open(TRANSPORT_TYPE bsFormat)    /*!< bitstream format (adif,adts,loas,...). */
{
  HANDLE_AACDECODER self;

  self = GetAacDecoder();
  if (self == NULL) {
    ESP_LOGE(TAG, "GetAacDecoder failed");
    goto bail;
  }
.....
}
```
self = GetAacDecoder() is always NULL.

Can you give me some help?

**Comment by MrBuddyCasino** [comment]
Sorry, this is not a support forum. You probably don't have enough memory left, because Mongoose OS needs some for itself.

**Comment by aifer2007** [comment]
Thanks.
