### ISSUE TITLE
Missing bluetooth settings in make menuconfig

### ISSUE THREAD

**Issue by FacepalmMute** [MrBuddyCasino/ESP32_MP3_Decoder#11]
The setting options for bluetooth are missing.

**Comment by MrBuddyCasino** [comment]
You have to manually enable Bluetooth Classic first.

**Comment by FacepalmMute** [comment]
Oh ok, my bad.
Thank you for the fast response.

**Comment by MrBuddyCasino** [comment]
np

**Comment by Bobylein** [comment]
Might sound stupid, but where to enable classic bluetooth? If I look under: "Component config -> bluetooth" I can't activate anything.
