### ISSUE TITLE
Icy-MetaData support

### ISSUE THREAD

**Issue by zajaklis** [MrBuddyCasino/ESP32_MP3_Decoder#18]
Per https://cast.readme.io/v1.0/docs/icy if header contains `Icy-MetaData: 1` server can send back some metadata which typically includes song title. 
After adding Icy-MetaData: 1 to headers ESP32 player plays ok and then goes mad and starts to blame with decoder errors:
 **Buffer underflow 
 lost synchronization**

Metadata feature could be great to show played track title on oled display.
Stream with metadata: http://live.pieci.lv/live19-hq.mp3
![untitled](https://user-images.githubusercontent.com/13708111/28305915-2e212284-6ba6-11e7-9740-c9812b073822.png)

**Comment by MrBuddyCasino** [comment]
I'm quite busy at the moment, so I'll probably not have the time to implement this. I'll accept well written pull requests though.
