### ISSUE TITLE
conversion from ESP8266

### ISSUE THREAD

**Issue by yo2ldk** [MrBuddyCasino/ESP32_MP3_Decoder#2]
not issue, nice project!

 can be this code somehow "translated" to esp32?

[https://github.com/karawin/Ka-Radio](url)

**Comment by MrBuddyCasino** [comment]
Didn't know that one, looks impressive! There are probably many things we could integrate.

**Comment by MrBuddyCasino** [comment]
Adding a list of stations and a web server are planned features, which I guess is what most people want. Closing this issue for now.
