### ISSUE TITLE
How to use PDM output?

### ISSUE THREAD

**Issue by paulo-raca** [MrBuddyCasino/ESP32_MP3_Decoder#22]
Hello,
Can you give any hints on what circuit I need to amplify the PDM output? 
Thanks!

**Comment by MrBuddyCasino** [comment]
Look at the sigma-delta reconstruction filter: https://github.com/MrBuddyCasino/ESP32_MP3_Decoder/blob/master/doc/filter_schematics.png

Then wire a normal analog amplifier to that filters output. Never tried it, but I think this should work.

**Comment by MrBuddyCasino** [comment]
Here is another link that might help: https://janostman.wordpress.com/audio-hacking-with-the-esp8266/
