### ISSUE TITLE
A2DP keep repeating same sound when calling on phone.

### ISSUE THREAD

**Issue by fanthos** [MrBuddyCasino/ESP32_MP3_Decoder#25]
I am using this project as bluetooth speaker. After connect my phone to ESP32, when I am making a call, the player keep repeating same sound until I stop calling.

The solution is call `renderer_stop` on a2dp receiving status 0.

Right now there is another problem. When `renderer_start` called, there's some noise before playing the audio. I am looking for a way to deal with that.

**Comment by fanthos** [comment]
I have current WIP code at https://github.com/fanthos/esp32-bt-iap.

**Comment by MrBuddyCasino** [comment]
Alright, wanna make a pull request?

**Comment by MrBuddyCasino** [comment]
Thanks for contributing, merged.
