### ISSUE TITLE
Unable to get it working in I2S Slave mode

### ISSUE THREAD

**Issue by pad52** [MrBuddyCasino/ESP32_MP3_Decoder#28]
Everything works as expected in master mode,
but if I try to set up Slave mode, in audio_render.c:
    i2s_mode_t mode = I2S_MODE_SLAVE | I2S_MODE_TX;

Esp32 is correctly not generating clock but waiting for it and replying with data,
hovewer the generated data is full of noise even if it's correctly synchronized.

**Comment by MrBuddyCasino** [comment]
This looks like an issue with the ESP-IDF, please open a ticket with them.
