### ISSUE TITLE
ini.h missing

### ISSUE THREAD

**Issue by newkit** [MrBuddyCasino/ESP32_MP3_Decoder#30]
Maybe this is just me being stupid, but where does ini.h come from?

Compiling the latest checkout in master gives me:
`ESP32_MP3_Decoder/components/playlist/./playlist.c:19:17: fatal error: ini.h: No such file or directory`

Any suggestion is much appreciated!

**Comment by MrBuddyCasino** [comment]
tried `git submodule init && git submodule update`?

**Comment by newkit** [comment]
Dooh, you are absolutely right. I was so sure that I did that but it turned out that this was missing. Sorry for bothering you.

**Comment by MrBuddyCasino** [comment]
np, glad it works now!
