### ISSUE TITLE
Work as pulseaudio sink over wifi?

### ISSUE THREAD

**Issue by Harvie** [MrBuddyCasino/ESP32_MP3_Decoder#34]
It would be nice if it was possible to use ESP32 as bluetooth/wifi speaker. So i can stream audio to it not only using bt, but also over wifi. From my Linux box, using pulseaudio.

**Comment by edgarmove** [comment]
You can try this on the server side:
https://superuser.com/questions/874631/streaming-pulseaudio-to-vlc-via-null-sink

**Comment by Harvie** [comment]
@edgarmove That's not plug and play.
