### ISSUE TITLE
Bluetooth and webradio

### ISSUE THREAD

**Issue by boonkerz** [MrBuddyCasino/ESP32_MP3_Decoder#35]
is it not possible to use both?
switch bluetooth on/off with an gpio toogle or web command?

**Comment by vibnwis** [comment]
HI there,
I am working on the same thing. My research tell me that the code will need to modified to separate them than switch to one another.

**Comment by juraj-ondruska** [comment]
Hi,
do you have some update regarding this? I'd like to do the same
