### ISSUE TITLE
Blue Tooth Enable

### ISSUE THREAD

**Issue by cr8myf8** [MrBuddyCasino/ESP32_MP3_Decoder#36]
Very cool project!  

I was able to build the project and flash it onto the sparkfun esp32 thing board.  I can play an MP3 stream with the built in DAC, but I can't enable the bluetooth in the menuconfig.  Any idea why the bluetooth is not an option?

**Comment by MrBuddyCasino** [comment]
You first have to enable the generic bluetooth support in the ESP32 config. Its somewhere in the component configuration menu I think.

**Comment by cr8myf8** [comment]
Thanks for the response.  I am new to the esp32 so I am sorry if my questions seem ignorant.  I was able to flash the esp32 with the bluetooth a2dp_sink example code.  The config menu showed some bluetooth options.  However, the configuration menu for this project is just blank.  Maybe I messed up the files.  I will try and clone the project again to see if that fixes the issue.

Configuration Menu for ESP32_MP3_Decoder
![screen shot 2017-12-10 at 3 26 42 pm](https://user-images.githubusercontent.com/11078135/33810137-93b93bba-ddbe-11e7-8b89-881b544f9401.png)

Configuration Menu for a2dp_sink
![screen shot 2017-12-10 at 3 29 09 pm](https://user-images.githubusercontent.com/11078135/33810189-1e5ccea8-ddbf-11e7-8e21-6a30ee8326f9.png)

**Comment by MrBuddyCasino** [comment]
Hmm, looks like they changed some stuff - possibly a v3 problem. Not sure when I get the time to look into it, you can try editing the kconfig file, there is condition in there that disables bluetooth speaker mode unless esp32 bt is enabled. Maybe they renamed it.

**Comment by MrBuddyCasino** [comment]
Updated code, please try again. Make sure to enable A2DP Sink in menuconfig.
