### ISSUE TITLE
The speaker does not ring

### ISSUE THREAD

**Issue by LilyGO** [MrBuddyCasino/ESP32_MP3_Decoder#37]
minicom shows the audio data in transit, but there is no volume. My din gain pin is not connected, and my module is max98357A

minicom:
E (94116) BT: BTA_AV_START_EVT status 0, suspending 0, init 0

I (94116) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x1
I (94126) BT_AV: a2dp audio_state_cb state 2
E (96146) BT_AV: audio data pkt cnt 100
E (98146) BT_AV: audio data pkt cnt 200
E (100146) BT_AV: audio data pkt cnt 300
E (102156) BT_AV: audio data pkt cnt 400
E (104166) BT_AV: audio data pkt cnt 500
E (106166) BT_AV: audio data pkt cnt 600
E (108166) BT_AV: audio data pkt cnt 700

**Comment by MrBuddyCasino** [comment]
Did you configure I2S output?

**Comment by LilyGO** [comment]
![screenshot_12](https://user-images.githubusercontent.com/31160602/33826594-73c1c52e-dea0-11e7-898a-6d6322405806.png)

**Comment by LilyGO** [comment]
I keep the I2S default settings, the rest there is a need to set the place?

**Comment by MrBuddyCasino** [comment]
Looks good. I suppose you already checked the pin connections. Do you have an oscilloscope? The I2S signals are quite fast and need decent electrical connections and short wires to work.

**Comment by LilyGO** [comment]
![img_20171212_090255](https://user-images.githubusercontent.com/31160602/33861629-bfcae878-df19-11e7-9bb1-b761f553dd0f.jpg)

**Comment by LilyGO** [comment]
Maybe my lead is really too long. thanks for your advice
