### ISSUE TITLE
Only getting white noise

### ISSUE THREAD

**Issue by physiii** [MrBuddyCasino/ESP32_MP3_Decoder#38]
I can connect but when I start streaming the speaker just makes white noise as if I'm just playing a blank audio file. Tried on both android and iphone with same result.

I am using [WROOM32](http://espressif.com/sites/default/files/documentation/esp-wroom-32_datasheet_en.pdf) with an I2S speaker. I've had it working before but I'm on a different computer and won't be back to that one for a couple days.

Any idea what is going on?

> I (548) bt_speaker: starting "ESP_SPEAKER"
> E (15728) BT: btm_sec_conn_req
> 
> E (15808) BT: btm_sec_connected
> 
> E (18758) BT: for SMP over BR max_key_size: 0x10,                        local_i_key: 0x07, local_r_key: 0x07
> 
> E (19028) BT: bta_av_rc_create ACP handle exist for shdl:0
> I (19028) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x0
> I (19028) BT_AV: a2dp conn_state_cb, state 1
> E (21028) BT: bta_av_link_role_ok hndl:x41 role:1 conn_audio:x0 bits:2 features:x824b
> 
> I (22708) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x2
> I (22718) BT_AV: a2dp audio_cfg_cb , codec type 0
> I (22718) BT_AV: audio player configured
> E (22738) BT: process_service_search_attr_rsp
> 
> E (27718) BT: bta_dm_rm_cback:0, status:0
> I (27718) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x0
> I (27718) BT_AV: a2dp conn_state_cb, state 2
> E (32338) BT: process_service_search_attr_rsp
> 
> E (32358) BT: bta_av_rc_opened allow incoming AVRCP connections:1
> E (32358) BT: bta_av_rc_opened rcb[1] shdl:1 lidx:1/0
> I (32368) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x0
> I (32368) BT_AV: avrc conn_state evt: state 1, feature 0x4b, [ac:cf:85:2a:7f:18]
> E (35418) BT: bta_av_proc_stream_evt: p_data is null
> E (35418) BT: bta_av_link_role_ok hndl:x41 role:1 conn_audio:x1 bits:1 features:x824b
> 
> E (35428) BT: bta_dm_rm_cback:0, status:0
> E (35428) BT: bta_dm_rm_cback:0, status:7
> E (35438) BT: BTA_AV_START_EVT status 0, suspending 0, init 0
> 
> I (35438) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x1
> I (35448) BT_AV: a2dp audio_state_cb state 2
> E (37788) BT_AV: audio data pkt cnt 100
> E (39788) BT_AV: audio data pkt cnt 200
> E (41788) BT_AV: audio data pkt cnt 300
> E (43788) BT_AV: audio data pkt cnt 400
> E (45788) BT_AV: audio data pkt cnt 500
> E (47788) BT_AV: audio data pkt cnt 600
> E (49788) BT_AV: audio data pkt cnt 700
> E (51788) BT_AV: audio data pkt cnt 800
> E (53788) BT_AV: audio data pkt cnt 900
> E (55588) BT: bta_av_proc_stream_evt: p_data is null
> E (55588) BT: bta_dm_rm_cback:0, status:6
> E (55588) BT: BTA_AV_SUSPEND_EVT status 0, init 0
> 
> I (55588) BT_APP_CORE: bt_app_task_handler, sig 0x1, 0x1
> I (55598) BT_AV: a2dp audio_state_cb state 0
>

**Comment by MrBuddyCasino** [comment]
No idea, I2S should work on all platforms. Best bet is to check with a scope or something.
