### ISSUE TITLE
How to change the pin

### ISSUE THREAD

**Issue by LilyGO** [MrBuddyCasino/ESP32_MP3_Decoder#39]
Sir, hello. Because my pin is not a lot, my GPIO 22 used other functions, so DATA can not be connected. I really wanted to implement Bluetooth music, but I did not find a way to change the pin's code. I hope to get your help, thank you very much. Wish you a Happy New Year!

**Comment by tonyp7** [comment]
No offense but this is not an issue and this is really lazy... Just search for GPIO_NUM_22 in the repository

https://github.com/MrBuddyCasino/ESP32_MP3_Decoder/blob/ca6344801fadfb7ec74fd71bc8b76bb6887f65df/components/audio_renderer/audio_renderer.c#L79

.... Boom just right there.

**Comment by MrBuddyCasino** [comment]
Thanks Tony!
