### ISSUE TITLE
implicit declaration of function 'ini_parse_stream'

### ISSUE THREAD

**Issue by Wittyt** [MrBuddyCasino/ESP32_MP3_Decoder#40]
Hi Michael,

  I am in the translation of the following error.
  _D:/path/to/ESP32_MP3/esp-idf-template/components/playlist/playlist.c: In function 'playlist_load_pls':
D:/path/to/ESP32_MP3/esp-idf-template/components/playlist/playlist.c:146:15: error: implicit declaration of function 'ini_parse_stream' [-Werror=implicit-function-declaration]
     int res = ini_parse_stream(pls_ini_reader, &file_start_ptr, pls_ini_handler, playlist->entries_vec);_

 Is it because I am missing a library?

Thank you！

**Comment by MrBuddyCasino** [comment]
Try `git submodule init && git submodule update`

**Comment by Wittyt** [comment]
Now it can work, Thank you！
