### ISSUE TITLE
Missing ini.h file

### ISSUE THREAD

**Issue by amigafan** [MrBuddyCasino/ESP32_MP3_Decoder#42]
Maybe this is just me being stupid, but where does ini.h come from?
When I try to build I got this error:
ESP32_MP3_Decoder/components/playlist/./playlist.c:19:17: fatal error: ini.h: No such file or directory
And I have tried: "git submodule init && git submodule update", in the esp-idf directory
Any suggestion is much appreciated! Thanks in advance.

**Comment by MrBuddyCasino** [comment]
Try executing "git submodule init && git submodule update" in the project directory, not esp-idf.

Von meinem iPhone gesendet

> Am 30.01.2018 um 21:45 schrieb amigafan <notifications@github.com>:
> 
> "git submodule init && git submodule update"

**Comment by amigafan** [comment]
When I try I get this error: fatal: Not a git repository (or any of the parent directories): .git

**Comment by MrBuddyCasino** [comment]
Well I guess you are in the .git directory? You can find out via `pwd`. If so. go one level higher with `cd ..`.

**Comment by amigafan** [comment]
![skaermbillede pa 2018-01-31 12-59-22](https://user-images.githubusercontent.com/35266489/35622005-a35307ea-0686-11e8-8fbe-f2964b7819e3.png)
 Still no luck

**Comment by MrBuddyCasino** [comment]
I'm afraid I have no idea. I would try to retry a `git clone` and repeat your steps. This looks like a git issue so I'm closing this for now.
