### ISSUE TITLE
Bluetooth speaker speaker no sound came out

### ISSUE THREAD

**Issue by LilyGO** [MrBuddyCasino/ESP32_MP3_Decoder#46]
Bluetooth has been successfully connected, and the serial port has been read music information. Pin has also been confirmed, but not the slightest sound.
![screenshot_2](https://user-images.githubusercontent.com/31160602/36652549-55c579e0-1aea-11e8-9dac-e9c7ac0f8318.png)
![img_20180226_115143](https://user-images.githubusercontent.com/31160602/36652569-72714ab0-1aea-11e8-8bbf-fb8d24c61fc3.jpg)
![img_20180226_115124](https://user-images.githubusercontent.com/31160602/36652572-76f202dc-1aea-11e8-857b-7d3e25ef51b2.jpg)

**Comment by MrBuddyCasino** [comment]
I can't make out the pins by the photos. Console output looks fine.

**Comment by LilyGO** [comment]
PIN 25 LRCK
PIN 26 BCLK
PIN 22 DATA

**Comment by LilyGO** [comment]
![img_20180301_164203](https://user-images.githubusercontent.com/31160602/36834592-4de08cc0-1d6e-11e8-9f1f-4906c4d44ae7.jpg)

**Comment by LilyGO** [comment]
I bought two 98357A last month and one last week. So I think my horn is too small, so I bought a horn. But unfortunately, from beginning to end a trace of Bluetooth device music came out.
