### ISSUE TITLE
how to use this with the arduino ide?

### ISSUE THREAD

**Issue by Primus007** [MrBuddyCasino/ESP32_MP3_Decoder#52]
is there any way to use this with the arduino ide?

**Comment by MrBuddyCasino** [comment]
I don't think so. What are you trying to do that you currently can't?

**Comment by Primus007** [comment]
I know myself well with the arduino ide :) Here I have to deal with completely new things with which I do not know. It is not so easy under Windows.
But thank you for your fast answer.

**Comment by MrBuddyCasino** [comment]
Yeah, Arduino is convenient. The ESP32 SDK is really nice though and they have examples for most things, and C isn't that hard. I can recommend it. Good luck!
