### ISSUE TITLE
NO rule to make target!! Not able flash the code . 

### ISSUE THREAD

**Issue by parmarravi** [MrBuddyCasino/ESP32_MP3_Decoder#56]
Hi,
I am having some trouble in my windows 10 pc  to compile this code .Whenever i am doing make , i am getting below result .Which i have no clue .How can i resolve it . Thank you in advance .
> make[1]: *** No rule to make target 'C:/msys32/home/ravi_/esp/esp-idf/examples/get-started/ESP32_MP3_Decoder/components/MerusAudio/MerusAudio.c', needed by 'MerusAudio.o'.  Stop.
> make: *** [C:\msys32\home\ravi_\esp\esp-idf/make/project.mk:468: component-MerusAudio-build] Error 2
>

**Comment by MrBuddyCasino** [comment]
Windows users are kindly asked to fix their own issues, its not something I use
