### ISSUE TITLE
Bluetooth option invisiable

### ISSUE THREAD

**Issue by evan2882** [MrBuddyCasino/ESP32_MP3_Decoder#68]
I am having the same problem posted by this person a year ago. Under Componet Config>Bluetooth, there is no Bluedroid Blutooth stack enabled option and I do not see activate bt speaker mode under WebRadio submenu either . I am using the latest firmware and IDF. 

Configuration Menu for ESP32_MP3_Decoder
![screen shot 2017-12-10 at 3 26 42 pm](https://user-images.githubusercontent.com/11078135/33810137-93b93bba-ddbe-11e7-8b89-881b544f9401.png)

_Originally posted by @cr8myf8 in https://github.com/MrBuddyCasino/ESP32_MP3_Decoder/issues/36#issuecomment-350587122_

**Comment by instalator** [comment]
Did you solve this problem?
