### ISSUE TITLE
SW volume control

### ISSUE THREAD

**Issue by kuzmanzs** [MrBuddyCasino/ESP32_MP3_Decoder#85]
Hi,

is it possible to control volume (I mean except ie. MAX98357A gain control pin)?

**Comment by MrBuddyCasino** [comment]
Not via software. Shouldn’t be hard to implement though.

**Comment by kuzmanzs** [comment]
Please could you give me some hint?
I think it should be put into **render_samples** method of audio_renderer.c where **i2s_write** happens or into audio_player's **audio_stream_consumer** method would be better place or?

**Comment by MrBuddyCasino** [comment]
That would probably be a good place. Its been quite some time since I've touched this code, so take this with a grain of salt.

**Comment by kuzmanzs** [comment]
yes, thanks
